// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pgjkchopswxpgprrakxy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBnamtjaG9wc3d4cGdwcnJha3h5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxNTY0OTgsImV4cCI6MjA1ODczMjQ5OH0.-7-SjDwVzlJtU6K_N3w-f2IQOAP0uz72oV3E8_FijIA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);